services:
  proxy:
    image: nginx:alpine
    container_name: dio_proxy
    ports:
      - "${APP_PORT:-4500}:80"
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    networks:
      - dio_net

  app:
    build: ./app
    container_name: dio_app
    environment:
      DB_HOST: db
      DB_USER: ${MYSQL_USER}
      DB_PASS: ${MYSQL_PASSWORD}
      DB_NAME: ${MYSQL_DATABASE}
    networks:
      - dio_net

  db:
    image: mysql:8.4
    container_name: dio_db
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./database/banco.sql:/docker-entrypoint-initdb.d/banco.sql:ro
      - dio_db_data:/var/lib/mysql
    networks:
      - dio_net

  adminer:
    image: adminer:latest
    container_name: dio_adminer
    ports:
      - "8081:8080"
    depends_on:
      - db
    networks:
      - dio_net

networks:
  dio_net:

volumes:
  dio_db_data:
